footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser lidar
    laser:
        {
            data_type: LaserScan,
            clearing: false,
            marking: false,
            topic: scan,
            inf_is_valid: true,
        }
    lidar:
        {
            data_type: PointCloud2,
            clearing: true,
            marking: true,
            topic: velodyne_points,
            min_obstacle_height: 0.2,
            max_obstacle_height: 1.5,
            inf_is_valid: false,
        }

inflation:
    inflation_radius: 1.0
